### ISSUE TITLE
Any way to keep HMR with node-integration?

### ISSUE THREAD

**Issue by georgiosd** [Rokt33r/ReactElectronExample#1]
As far as I can see, HMR will only work with webpack-dev-server, which means that modules are loaded over the network and electron's web integration stops working.

Am I missing something?

**Comment by Rokt33r** [comment]
https://github.com/Rokt33r/ReactElectronExample/blob/master/browser/main/index.js#L32-L43

**Comment by Rokt33r** [comment]
You have to intercept refreshing. Also, you should provide some context(like `window`) to replace the modified module instance with the old one.

```js
window.myModule = require('./~~/some-node-module.js')

if (module.hot) {
  // This will prevent refreshing if './~~/some-node-module.js' is modified
  module.hot.accept('./~~/some-node-module.js', () => {
    window.myModule = require('./~~/some-node-module.js')
  })
}

function doSomethingWithModule () {
  window.myModule.doSpecificThing()
}
```

https://github.com/Rokt33r/ReactElectronExample/blob/master/browser/main/index.js#L32-L43

**Comment by georgiosd** [comment]
Thank you.
